language: android
sudo: false

notifications:
  email: false

cache: 
  directories: 
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
    - tools
    - platform-tools

    - build-tools-26.0.1
    - android-26

    - build-tools-26.0.0
    - build-tools-25.0.1
    - android-25

    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
#    - sys-img-x86-google_apis_playstore-26

licenses: 
    - android-sdk-preview-license-52d11cd2
    - android-sdk-license-c81a61d9
    - android-sdk-license-.+
    - google-gdk-license-.+

before_cache: 
  - "rm -f $HOME/.gradle/caches/modules-2/modules-2.lock"

before_install: 
    - "chmod +x gradlew"

before_script:
    - echo "Travis branch is $TRAVIS_BRANCH"
 #   - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a
 #   - emulator -avd test -no-skin -no-audio -no-window &
 #   - android-wait-for-emulator
 #   - adb shell input keyevent 82 &

script:
    - "./gradlew clean build connectedCheck --stacktrace"